defaultNamespace: longhorn-system
helm:
  releaseName: longhorn
  chart: longhorn
  repo: https://charts.longhorn.io
  version: 1.4.4
values:
  deletingConfirmationFlag: true  
diff:  
  comparePatches:  
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: engineimages.longhorn.io
    operations:
    - {"op":"remove", "path":"/status/acceptedNames/kind"}
    - {"op":"remove", "path":"/status/acceptedNames/plural"}
    #jsonPointers: # jsonPointers allows to ignore diffs at certain json path
    #- "/spec/template/spec/priorityClassName"
    #- "/spec/template/spec/tolerations"


