defaultNamespace: longhorn-system
helm:
  releaseName: longhorn
  chart: longhorn
  repo: https://charts.longhorn.io
  version: 1.4.4
  valuesFiles:
    - values.yaml
diff:  
  comparePatches:  
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: engineimages.longhorn.io
    operations:
    - {"op":"remove", "path":"/status/acceptedNames/kind"}
    - {"op":"remove", "path":"/status/acceptedNames/plural"}
    - {"op":"remove", "path":"/status/conditions"}
    - {"op":"remove", "path":"/status/storedVersions"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: nodes.longhorn.io
    operations:
    - {"op":"remove", "path":"/status/acceptedNames/kind"}
    - {"op":"remove", "path":"/status/acceptedNames/plural"}
    - {"op":"remove", "path":"/status/conditions"}
    - {"op":"remove", "path":"/status/storedVersions"}
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: volumes.longhorn.io
    operations:
    - {"op":"remove", "path":"/status/acceptedNames/kind"}
    - {"op":"remove", "path":"/status/acceptedNames/plural"}
    - {"op":"remove", "path":"/status/conditions"}
    - {"op":"remove", "path":"/status/storedVersions"}
