defaultNamespace: longhorn-system
helm:
  releaseName: longhorn
  chart: longhorn
  repo: https://charts.longhorn.io
  version: 1.3.1
diff:  
  comparePatches:  
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    operations:
    - {"op":"remove", "path":"/status/"}
